swagger: "2.0"
info:
  description: "This is a sample BasketService server.  "
  version: "1.0.0"
  title: "Basket Service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "berfu.efe@ozu.edu.tr"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api/v1/basket-service-api"
tags:
  - name: "category"
    description: "Categories of the Basket Service"
  - name: "product"
    description: "Products of the Basket Service"
  - name: "user"
    description: "Users of the Basket Service "

schemes:
  - "http"
paths:
  /user/signUp:
    post:
      tags:
        - "user"
      summary: "create a new user"
      description: "This can only be done by the logged in user for sign up to the service."
      operationId: "signUp"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Created user object with specified information. Note that role field should be set 'Admin' or 'User'"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid input"
          

  /user/login:
    post:
      tags:
        - "user"
      summary: "Users can be login to the service "
      description: "This can be done to login to the basket service"
      operationId: "login"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User email and password to login to the service"
          required: true
          schema:
            $ref: "#/definitions/Login"
      responses:
        "200":
          description: "successful operation, should return a token"
          schema:
            type: "string"
        "400":
          description: "Invalid username/password supplied"          

  /category/upload:
    post:
      tags:
        - "category"
      summary: "Upload a csv file to add categories to the service"
      description: "Upload categories with csv file"
      operationId: "uploadCategoryFile"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - in: formData
          name: "categories.csv"      
          required: true
          type: file
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Category"
        "405":
          description: "Invalid input"
          
  /category/list:
    get:
      tags:
        - "category"
      summary: "List categories in the service"
      description: ""
      operationId: "listCategories"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Category"
        "405":
          description: ""


  /product/create:
    post:
      tags:
        - "product"
      summary: "Add products to the service"
      description: ""
      operationId: "createProduct"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "products needs to be added one by one"
          required: true
          schema:
            $ref: "#/definitions/ProductWithoutCategoryName"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "405":
          description: "Invalid input"

  /product/list:
    get:
      tags:
        - "product"
      summary: "List all products in the service"
      description: ""
      operationId: "listProduct"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "405":
          description: ""
          
  /product/:id:
    get:
      tags:
        - "product"
      summary: "Gets the products in the service with given product id" 
      description: ""
      operationId: "getProductByID"
      produces:
        - "application/json"

      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "405":
          description: "Invalid input"

  /product/searchByProductName/:name:
    get:
      tags:
        - "product"
      summary: "Gets the products in the service with given product name"
      description: ""
      operationId: "searchAndGetProductByName"
      produces:
        - "application/json"

      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "405":
          description: "Invalid input"          

  /product/searchByProductID/:id:
    get:
      tags:
        - "product"
      summary: "Searches and gets the products in the service with given product id"
      description: ""
      operationId: "searchAndGetProductByID"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "405":
          description: "Invalid input"     
          
  /product/deleteProductByID/:id:
    delete:
      tags:
        - "product"
      summary: "Deletes the products in the service with given product id"
      description: ""
      operationId: "deleteProductByID"
      responses:
        "200":
          description: "successful operation"
        "405":
          description: "Invalid input"    

  /product/updateProductByID/:id:
    put:
      tags:
        - "product"
      summary: "Updates the products in the service with given product id"
      description: ""
      operationId: "updateProductByID"
      parameters:
        - in: "body"
          name: "body"
          description: "Updates the products with given productID"
          required: true
          schema:
            $ref: "#/definitions/ProductWithoutCategoryName"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "405":
          description: "Invalid input"  
          
  /basket/add:
    post:
      tags:
        - "basket"
      summary: "Add basket items to the service"
      description: ""
      operationId: "addItemToBasket"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "basket items need to be added one by one"
          required: true
          schema:
            $ref: "#/definitions/BasketItem"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/BasketItem"
        "405":
          description: "Invalid input"          
          
  /basket/list/:id:
    get:
      tags:
        - "basket"
      summary: "List all items in the basket with given user id"
      description: ""
      operationId: "listBasketItemOfSpecificUser"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/BasketItem"
        "405":
          description: "invalid input" 
          
  /basket/deleteBasketItemByID/:id:
    delete:
      tags:
        - "basket"
      summary: "Deletes the products in the basket with given product id"
      description: ""
      operationId: "deleteBasketItemByProductID"
      responses:
        "200":
          description: "successful operation"
        "405":
          description: "Invalid input"           

  /basket/updateBasketItemByID/:id:
    put:
      tags:
        - "basket"
      summary: "Updates the products in the basket with given product id"
      description: ""
      operationId: "updateBasketItemByProductID"
      parameters:
        - in: "body"
          name: "body"
          description: "Updates the products in the basket with given productID"
          required: true
          schema:
            $ref: "#/definitions/BasketItem"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/BasketItem"
        "405":
          description: "Invalid input" 
          


definitions:
  Category:
    type: "object"
    required:
      - "category_id"
    properties:
      category_id:
        type: "integer"
        format: "uint"
      category name:
        type: "string"
        format: "string"
      product:
        type: "object"
        
        
  CategoryWithoutName:
    type: "object"
    required:
      - "category_id"
    properties:
      category_id:
        type: "integer"
        format: "uint"


  Product:
    type: "object"
    required:
      - "product_id"
    properties:
      product_id:
        type: "integer"
        format: "uint"
      product_name:
        type: "string"
      product_stock:
        type: "integer"
        format: "int"
      product_price:
        type: "number"
        format: "float64"
      product_stock_code:
        type: "string"
      product_type:
        type: "string"
      product_color:
        type: "string"
      product_size:
        type: "string"
      product_material:
        type: "string"
      gender:
        type: "string"
      Category:
        type: "object"
        $ref: "#/definitions/Category"      
        
  ProductWithoutCategoryName:
    type: "object"
    required:
      - "product_id"
    properties:
      product_id:
        type: "integer"
        format: "uint"
      product_name:
        type: "string"
      product_stock:
        type: "integer"
        format: "int"
      product_price:
        type: "number"
        format: "float64"
      product_stock_code:
        type: "string"
      product_type:
        type: "string"
      product_color:
        type: "string"
      product_size:
        type: "string"
      product_material:
        type: "string"
      gender:
        type: "string"
      Category:
        type: "object"
        $ref: "#/definitions/CategoryWithoutName"  
       
        
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "uint"
      email:
        type: "string"
      password:
        type: "string"
      role:
        type: "string"

  Login:
    type: "object"
    required:
      - email
      - password
    properties:
      email:
        type: "string"
      password:
        type: "string"
        
  BasketItem:
    type: "object"
    required:
      - id
      - quantity
    properties:
      id:
        type: "integer"
        format: "uint"
      quantity: 
        type: "integer"
        format: "int"
      Product:
        type: "object"
        $ref: "#/definitions/ProductWithOnlyID"
      User:
        type: "object"
        $ref: "#/definitions/UserWithOnlyID"    
        
  ProductWithOnlyID:
    type: "object"
    required:
      - id
    properties:
      id:
        type: "integer"
        format: "uint"

  UserWithOnlyID:
    type: "object"
    required:
      - id
    properties:
      id:
        type: "integer"
        format: "uint"
